apiVersion: v1
kind: Service
metadata:
  name: golang-simple-server
  labels:
    app: golang-simple-server
    tier: service
spec:
  # use NodePort here to be able to access a port on each node
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: golang-simple-server